### ISSUE TITLE
Example doesn't run on client

### ISSUE THREAD

**Issue by jimmiebtlr** [poetic/react-material-ui#1]
Error occurs on this line

```
var React = (typeof window !== "undefined" ? window['React']['require'] : typeof global !== "undefined" ? global['React']['require'] : null)("react");
```

and amounts to not finding window['React'].

**Comment by codeNgamer** [comment]
@jimmiebtlr what version of meteor are you using? That line is intended to be a fix for the meteor update 1.1.0.3

**Comment by jimmiebtlr** [comment]
```
cat .meteor/release 
METEOR@1.1.0.3
```

Looks like I'm on 1.1.0.3

**Comment by jimmiebtlr** [comment]
I'll look more in depth if the cause isn't obvious to you.

**Comment by jimmiebtlr** [comment]
commit cd336fc6c936d446d838af9f09f606f5f73c64ee

Runs fine for me on version 1.1.0.3, commit f81566aa18408cc180afbbbaba64952033de41d0 breaks it for me.

**Comment by rdagger** [comment]
Example fails on Meteor 1.2.0.2 with error:
Uncaught TypeError: Cannot read property 'component' of undefined

**Comment by codeNgamer** [comment]
@rdagger material-ui changed the way themes work now. Please see: http://material-ui.com/#/customization/themes 

version 0.4 of this package has since been updated to reflect these changes

**Comment by codeNgamer** [comment]
@rdagger please see #6 . I'll be closing this issue now in favor of #6, please post related issues there
