### ISSUE TITLE
Example crashing

### ISSUE THREAD

**Issue by VinceBT** [poetic/react-material-ui#7]
Hello :)

I am trying to develop a react app and I wanted to start using your package but the example doesn't work and I can't figure out how to solve this problem and go on.

I have done all these steps as you told : 
- `meteor add react`
- `meteor add react-template-helper`
- `meteor add poetic:react-material-ui`

But I get `ReferenceError: mui is not defined at todo-tm.jsx:1:11`

Thanks by advance for any help

**Comment by JohnRodney** [comment]
@BTVincent can you link a repo with the example behavior?

**Comment by codeNgamer** [comment]
@BTVincent please see #6 . Also, closing this in favor of that issue. Thanks
